### PR TITLE
Mseng10 GitHub actions

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
@mseng10

**Review by jhlegarreta — COMMENTED** [review]
Looks like this commit c0cc6e455998f882f0132e4e8a26e8eb5076866d is unrelated. Would it be better to submit it as a separate PR?

Should the Azure Pipelines config file be removed, the builds deactivated and the badge removed?

**Comment by thewtex** [comment]
> Looks like this commit c0cc6e4 is unrelated. Would it be better to submit it as a separate PR?

These were already in the *SimpleITK* repository -- pushed to `master`.

> Should the Azure Pipelines config file be removed, the builds deactivated and the badge removed?

Good catch @jhlegarreta

**Review by blowekamp — APPROVED** [review]
Looks Great! Thanks for the PR! Sorry I missed this one.

**Pull request merged**
